services:
  - type: web
    name: financial-literacy-website
    env: php
    plan: free
    repo: https://github.com/Joel5255/Tenant-website.git
    rootDir: .
    buildCommand: "composer install --no-dev"
    startCommand: "php -S 0.0.0.0:$PORT -t ."
    envVars:
      - key: PORT
        value: 10000
    healthCheckPath: /index.html
